apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-app
  namespace: openshift-gitops  
spec:
  project: default
  source:
    repoURL: https://github.com/CSA-RH/observability-demo-framework.git    
    path: install/helm/wave-1
    targetRevision: feature/installation
    helm:
      valueFiles:
        - obs-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: obs-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
