apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:  
  generation: 1
  labels:
    operators.coreos.com/loki-operator.openshift-operators-redhat: ""
  name: loki-operator
  namespace: openshift-operators-redhat
spec:
  channel: stable-6.1
  installPlanApproval: Automatic
  name: loki-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: loki-operator.v6.1.1
---
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: loki
  namespace: openshift-logging
spec:
  managementState: Managed
  size: 1x.demo
  storage:
    schemas:
      - effectiveDate: '2022-06-01'
        version: v12
      - effectiveDate: '2024-04-02'
        version: v13
    secret:
      name: logging-loki-azure
      type: azure
  storageClassName: managed-csi
  tenants:
    mode: openshift-logging