apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: openshift-gitops  
spec:
  project: default
  source:  
    repoURL: https://github.com/CSA-RH/observability-demo-framework.git
    targetRevision: feature/installation
    path: install/gitops/waves
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: obs-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true