apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wave-0-app
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CSA-RH/observability-demo-framework.git    
    path: install/helm/wave-0
    targetRevision: feature/installation
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true