apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coo
  namespace: openshift-gitops  
spec:
  project: default
  source:
    repoURL: https://github.com/CSA-RH/observability-demo-framework.git
    path: install/helm/wave-0
    targetRevision: feature/installation
  destination:
    server: https://kubernetes.default.svc
    namespace: obs-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true